Multiple Card Loading in Studio
IllusionMods/DragAndDrop pull request #14
Opened 2024-06-09 15:42 UTC by Timo713

This PR is related to this issue: https://github.com/IllusionMods/DragAndDrop/issues/12

Thanks to the power of AI, I managed to edit this plugin to allow for multiple card loading in KK studio, it adds a new method for loading all the selected cards in a folder whenever they're dragged over the selected slots in studio. I've checked and it hasn't broken any other functionalities yet, but you're free to review the code and edit it as it might need some polishing.

I tried to add the option to load them into the classroom screen slots too but there's no handler for it yet and without any references on how that screen works I have no idea on what to work with.

2024-06-09 17:47 UTC, ManlyMarco reviewed
Thanks for the PR! Did you build and test these changes in game? I'm pretty sure this won't compile and will have issues outside of studio since it will load each character card onto the same character.

2024-06-09 18:04 UTC, Timo713 commented
Yes, I've tested it already and no problems so far, this is the one I'm using, i'll include it in case you want to test it too.
[DragAndDropMultipleCardLoading.zip](https://github.com/user-attachments/files/15753612/DragAndDropMultipleCardLoading.zip)

2024-06-28 20:37 UTC, ManlyMarco reviewed
Sorry I went silent about this PR, it works but I didn't merge it yet because it only works for KK and not other games, but that's partially because the overall structure of this plugin isn't ideal. If you could make it also at least work in KKS (ideally also AI and HS2) I would merge it.

2024-06-28 20:37 UTC, ManlyMarco commented on src/DragAndDrop.Core/CardHandlerMethods.cs
> +        public virtual void Character_LoadMultiple(List<string> paths, POINT pos, byte sex) { }
I wouldn't add this to the API since it's only useful in one specific case.

2024-07-05 19:20 UTC, Timo713 commented
I guess I managed to make it work on the other games too, I tested on all of them and no problems so far. The only game I didn't test was PH and there's no need to add compatibility for EC since it has no studio.

I also took the liberty to implement the same feature for coordinate loading, so, now you can grab multiple coordinate cards into character slots and each of them will all be loaded separately. Great for previewing lots of clothing and characters!

2024-07-06 14:43 UTC, ManlyMarco requested changes
Looks like you forgot to update StudioHandler for Sunshine, build fails.

2024-07-06 15:37 UTC, Timo713 commented
Woops! sorry! it should be fixed now.

2024-07-06 18:40 UTC, ManlyMarco approved these changes
It works, thank you for the PR!

2024-07-06 18:46 UTC, merged